"""Add User avatar and Task archived flags

Revision ID: 0486d7c858d7
Revises: c41f67d0256a
Create Date: 2026-04-14 09:08:38.826155

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0486d7c858d7'
down_revision = 'c41f67d0256a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('archived', sa.Boolean(), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avatar_url', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('avatar_url')

    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_column('archived')

    # ### end Alembic commands ###
