"""Add TodoList and Task association

Revision ID: 3df8aa43b774
Revises: e840dfafe0e1
Create Date: 2026-04-14 10:39:37.631400

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3df8aa43b774'
down_revision = 'e840dfafe0e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('todo_list',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='fk_list_user_id'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_todo_list'))
    )
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('list_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_task_list_id', 'todo_list', ['list_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_constraint('fk_task_list_id', type_='foreignkey')
        batch_op.drop_column('list_id')

    op.drop_table('todo_list')
    # ### end Alembic commands ###
