"""Add TodoList and list attribution

Revision ID: 68a4244ad97d
Revises: 3df8aa43b774
Create Date: 2026-04-14 14:41:14.813064

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68a4244ad97d'
down_revision = '3df8aa43b774'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_task_list_id'), type_='foreignkey')
        batch_op.create_foreign_key('fk_task_list_id', 'todo_list', ['list_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('todo_list', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todo_list', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_constraint('fk_task_list_id', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_task_list_id'), 'todo_list', ['list_id'], ['id'])

    # ### end Alembic commands ###
