"""Add archived_at payload flag

Revision ID: 863a2a6d60f2
Revises: 0486d7c858d7
Create Date: 2026-04-14 09:33:08.072704

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '863a2a6d60f2'
down_revision = '0486d7c858d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('archived_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_column('archived_at')

    # ### end Alembic commands ###
